add code 2125858
juanrubio110729/ejemploapi-ds2 pull request #17
Opened 2024-02-28 19:08 UTC by ccgg1997

2024-03-03 16:27 UTC, ManuhCardoso1501 requested changes
You made unnecessary changes  🦡

2024-03-04 23:59 UTC, ccgg1997 commented
ready.

2024-03-05 00:38 UTC, frank1192 commented
hola, aun no se ven los cambios solicitados en el pull

2024-03-05 00:40 UTC, ccgg1997 commented
Hola, ya no mande, package-lock.json. 
El cambio que esta es el espacio que elimine en el git ignore

2024-03-05 01:13 UTC, juanrubio110729 requested changes
Aun no has removimo el cambio en el .gitignore. No debes alterar ningun otro archivo

2024-03-05 01:33 UTC, ccgg1997 commented
ya le di push con el espacio del git ignore, pero no me actualiza, alguien me podria dar una manito ?
o cierro el pr y abro otro ?

2024-03-05 01:43 UTC, closed without merging