Ervin Caravali Ibarra 192568
juanrubio110729/ejemploapi-ds2 pull request #20
Opened 2024-02-29 19:34 UTC by ErvinCaravali

Hola soy Ervin Caravali Ibarra y esta es mi tarea mi codigo es 1925648.

2024-03-03 16:31 UTC, ManuhCardoso1501 requested changes
You made unnecessary changes  🔪

2024-03-04 16:00 UTC, frank1192 requested changes
hubieron cambios innecesarios y añadiste un archivo no correspondiente package-lock.json🔪
vuelve a hacer el commit sin este archivo, con esto en clase ya podríamos aprobar tu solicitud de merge , cuando ya hagas esos cambios, salu2

2024-03-04 16:09 UTC, ErvinCaravali commented
Hola ya la hice mira el pull request numero 30.

El lun., 4 de marzo de 2024 11:00 a. m., FrankDvop ***@***.***>
escribió:

> ***@***.**** requested changes on this pull request.
>
> hubieron cambios innecesarios y añadiste un archivo no correspondiente
> package-lock.json🔪
> vuelve a hacer el commit sin este archivo, con esto en clase ya podríamos
> aprobar tu solicitud de merge , cuando ya hagas esos cambios, salu2
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/juanrubio110729/ejemploapi-ds2/pull/20#pullrequestreview-1914698888>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARN7QUMKYZXVPCZM5GYGANTYWSLCJAVCNFSM6AAAAABEAQ7Q6KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMJUGY4TQOBYHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-05 00:03 UTC, juanrubio110729 approved these changes
Por fin, todo ok 👌

2024-03-05 00:39 UTC, merged