feature/2122913
juanrubio110729/ejemploapi-ds2 pull request #52
Opened 2024-03-04 23:17 UTC by JuanSilva25

2024-03-04 23:44 UTC, OviedoSebastian approved these changes
ok

2024-03-05 00:07 UTC, juanrubio110729 requested changes
Haz eliminado archivos de otra persona, corregir con otro commit

2024-03-05 00:24 UTC, juanrubio110729 requested changes
Haz eliminado una carpeta previamente en el main, por favor corregirlo y nuevamente hacer commit

2024-03-05 00:49 UTC, frank1192 approved these changes
all is good

2024-03-05 00:55 UTC, frank1192 commented
> Haz eliminado archivos de otra persona, corregir con otro commit

juan, ya hizo el commit, aprobalo

2024-03-05 01:01 UTC, SilkenBread approved these changes

2024-03-05 01:01 UTC, merged