add 2127830 student
juanrubio110729/ejemploapi-ds2 pull request #6
Opened 2024-02-27 01:07 UTC by JoseM-18

2024-02-29 14:53 UTC, ChristianV2426 requested changes
Remember to follow the pattern "feature/codigo" or "feature/nombre_estudiante" for the branch name.

2024-03-05 00:30 UTC, juanrubio110729 approved these changes
ok 👌

2024-03-05 00:31 UTC, frank1192 approved these changes
todo esta bien, pero el nombre de la rama feature debria ir con tu codigo, pero de resto todo bien

2024-03-05 00:33 UTC, juanrubio110729 approved these changes

2024-03-05 00:34 UTC, juanrubio110729 approved these changes

2024-03-05 00:35 UTC, merged